name: Test performance of skops persistence

on:
  pull_request:
  schedule:
    - cron:  '0 9 * * 0'  # every sunday at 9:00 UTC
  workflow_dispatch:

jobs:
  check-persistence-performance:

    runs-on: ubuntu-latest
    if: "github.repository == 'skops-dev/skops'"

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install requirements
      run: |
        pip install .[tests]
        pip --version
        pip list
    - name: Run persistence performance checks
      run: python scripts/check_persistence_performance.py
